### ISSUE TITLE
Update not working

### ISSUE THREAD

**Issue by CyrilleB79** [ibrahim-s/searchWith#10] opened 2023-03-20 07:52 UTC
Hello

The add-on update does not work (at least when updated via Add-on Updater).
Old version: 2.3
New version: 2.4

Here is the relevant part of the log:
```
DEBUG - addonHandler._getAvailableAddonsFromPath (08:44:08.894) - MainThread (14664):
Loading add-on from C:\Users\Cyrille\AppData\Roaming\nvda\addons\searchWith
DEBUG - addonHandler.Addon.__init__ (08:44:08.894) - MainThread (14664):
Using manifest translation from C:\Users\Cyrille\AppData\Roaming\nvda\addons\searchWith\locale\fr\manifest.ini
DEBUG - addonHandler._getAvailableAddonsFromPath (08:44:08.895) - MainThread (14664):
Found add-on searchWith - 2.3. Requires API: (2019, 3, 0). Last-tested API: (2023, 1, 0)
DEBUG - addonHandler._getAvailableAddonsFromPath (08:44:08.895) - MainThread (14664):
Loading add-on from C:\Users\Cyrille\AppData\Roaming\nvda\addons\searchwith.pendingInstall
DEBUG - addonHandler.Addon.__init__ (08:44:08.895) - MainThread (14664):
Using manifest translation from C:\Users\Cyrille\AppData\Roaming\nvda\addons\searchwith.pendingInstall\locale\fr\manifest.ini
ERROR - addonHandler.Addon.completeInstall (08:44:08.897) - MainThread (14664):
Failed to complete addon installation for searchwith
Traceback (most recent call last):
  File "addonHandler\__init__.pyc", line 352, in completeInstall
FileExistsError: [WinError 183] Impossible de créer un fichier déjà existant: 'C:\\Users\\Cyrille\\AppData\\Roaming\\nvda\\addons\\searchwith.pendingInstall' -> 'C:\\Users\\Cyrille\\AppData\\Roaming\\nvda\\addons\\searchwith'
DEBUG - addonHandler._getAvailableAddonsFromPath (08:44:08.909) - MainThread (14664):
Found add-on searchwith - 2.4. Requires API: (2019, 3, 0). Last-tested API: (2023, 1, 0)
```

I wonder if the culprit is the install task, keeping resources open in the old folder?

Cc @josephsl for add-on updater part in case there would be something, but I do not think so.

**Comment by josephsl** [comment] 2023-03-20 15:58
Hi, caused by add-on manifest and package name mismatch – package name says “searchWith” whereas manifest name field says “searchwith”. I advise a 2.5 release to correct this issue. Thanks, and in the meantime, remove 2.3, restart NVDA, install 2.4, and restart NVDA again. Thanks.

**Comment by ibrahim-s** [comment] 2023-03-20 18:55
Hi Cyrille and Joseph
Thank you for your information
But really, the addon store did not accept the submition of the addon except when I changed the name of the addon to lower case, and may be that was the reason.
Now if I understand you well Joseph, I have to make a pull request to addon store, not through an issue, and change the folder name of the addon in the store to camel case , as well as returning the old name or id of the addon as it was before, did I got you right?
thank you in advance

**Comment by josephsl** [comment] 2023-03-20 19:20
Hi, if you would like to use searchWith (camel case) for add-on ID’s, then yes, you must send a pull request to change the add-on ID to the new one, and then submit version 2.4. If you want to keep using searchwith (all lower case), then we must inform people to uninstall 2.3, restart NVDA, install 2.4, and then restart NVDA right after to avoid the traceback shown here. This is why I asked everyone to wait until lowercase to uppercase conversion is complete before submitting new ad-don releases via isuses. Thanks.

**Comment by ibrahim-s** [comment] 2023-03-20 19:45
Hi Joseph
Sorry, may be I have missed your advice for waiting until his issue has been resolved.
things now seems more clear, thanks , and appreciate your role in this community.

**Comment by josephsl** [comment] 2023-03-20 19:53
Hi, sent a reminder to add-ons list. Do let us know (either here or on add-ons list) as to what the actual add-on manifest name field should say as it will determine add-on ID on the store. Thanks for understanding.

**Comment by ibrahim-s** [comment] 2023-03-20 20:12
Hi Joseph
I think it is more appropriate to keep with the old name, meaning camel case 'searchWith', as addon name and as an ID addon on the store.
 I will wait until this issue is resolved, and thanks again for your help.

**Comment by ibrahim-s** [comment] 2023-03-24 20:30
After Joseph has made a pull request on the addon store, to change the ID of the addon on the store to camel case, performed the following test:
- make a new version 2.5 of the addon, with the old name in manifest 'searchWith'(camel case)
- make sure also the current installed version is 2.3, that includes old name also in manifest
- check for add-ons update through tools menu in NVDA
- 2.5 version shows up
- Press enter to update
- Update completed without errors.
Thus I close the issue , and thanks Joseph for help.

**Closed by ibrahim-s** 2023-03-24 20:30 UTC

**Comment by CyrilleB79** [comment] 2023-03-24 22:08
On my side, Add-on Updater used with source=community website still offers Search With version 2.4 and not 2.5.

Anyway, setting the source on add-on store, the version 2.5 is offered. And the add-on is installed without error. Installing manually the version 2.5 is also successful.

So I confirm that on SearchWith side, the issue is fixed.

The remaining issue is the versions offered by Add-on Updater with source set on community website. Cc @josephsl

**Comment by josephsl** [comment] 2023-03-24 22:19
Hi, it’s a combination of legacy endpoint used by community add-ons update source and editing a certain json file used by Add-on Updater. For all intents and purposes, once ad-don store is more broadly available, community ad-dons update source will be declared legacy from Add-on Updater, but until then, I’ll keep an eye on other add-on update issues from my side throughout this weekend (not in April as I will be busy the entire month). Thanks.

**Comment by CyrilleB79** [comment] 2023-03-25 13:20
OK. Just for completeness, today add-on updater set on community website source offers the version 2.5. All is fine.

Also @josephsl you write:
> For all intents and purposes, once ad-don store is more broadly available, community ad-dons update source will be declared legacy from Add-on Updater, but until then, I’ll keep an eye on other add-on update issues from my side throughout this weekend (not in April as I will be busy the entire month). Thanks.

Unless I am mistaken, the community website source will remain the main one during the next weeks and add-on store will remain experimental until NVDA ships with the integrated client side of the add-on store. Taking into account the following points:
* there are currently many issues with the updates through the community website source
* many people will have to update when NVDA 2023.1 stable is released which is likely to be soon
* you are not available during the next month
Would you consider designate someone to do the very likely required maintenance of Add-on Updater future issues when using community website source? Maybe Luke?


*

**Comment by josephsl** [comment] 2023-03-25 13:56
Hi, “experimental” tag will be removed from add-on store source once NVDA alpha snapshots include store client. As for issues with updating add-ons via community add-ons update source, I hope to resolve most issues (dealing with add-on keys) this weekend. Thanks.
